#!/usr/bin/env ruby

require 'open-uri'

base_url = "http://api.crossref.org"

def trim_if_url(doi)
  s = doi.dup
  if doi.start_with?("https://doi.org/") or doi.start_with?("http://doi.org/")
    s.slice!("https://doi.org/")
    s.slice!("http://doi.org/")
  end
  return s
end

def remove_underscore(bib)
  strs = bib.split(",")
  strs[0].tr!("_", "")
  return strs.join(",")
end

for doi,i in ARGV.each_with_index
  doi = trim_if_url(doi)
  url = URI.encode("#{base_url}/works/#{doi}/transform/application/x-bibtex")
  begin
    open(url) do |f|
      bib = f.read
      if i > 0 then puts '' end
      puts remove_underscore(bib)
    end
  rescue => error
    puts error
    STDERR.puts "Error: Cannot find DOI #{doi}"
    exit 1
  end
end
